version: '3'
services:
  api:
    build: ./api
    ports:
      - "3306:3306"
    volumes:
      - .:/code/api
  hapi:
    build: ./hapi
    ports:
      - "8000:8000"
    volumes:
      - .:/code/hapi