-- MySQL Script generated by MySQL Workbench
-- Sun 15 Apr 2018 04:20:09 PM CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DB_Lab
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DB_Lab` ;

-- -----------------------------------------------------
-- Schema DB_Lab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_Lab` DEFAULT CHARACTER SET utf8 ;
USE `DB_Lab` ;

-- -----------------------------------------------------
-- Table `DB_Lab`.`nonPolitician`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Lab`.`nonPolitician` ;

CREATE TABLE IF NOT EXISTS `DB_Lab`.`nonPolitician` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `picture` INT NULL DEFAULT NULL,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Lab`.`party`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Lab`.`party` ;

CREATE TABLE IF NOT EXISTS `DB_Lab`.`party` (
  `partyId` INT NOT NULL AUTO_INCREMENT,
  `partyName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`partyId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Lab`.`platform`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Lab`.`platform` ;

CREATE TABLE IF NOT EXISTS `DB_Lab`.`platform` (
  `platformId` INT NOT NULL AUTO_INCREMENT,
  `platformName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`platformId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Lab`.`politicians`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Lab`.`politicians` ;

CREATE TABLE IF NOT EXISTS `DB_Lab`.`politicians` (
  `polId` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `picture` INT NULL DEFAULT NULL,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `partyId` INT NOT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `website` VARCHAR(45) NULL DEFAULT NULL,
  `platformId` INT NULL DEFAULT NULL,
  `tenure` INT NULL DEFAULT NULL,
  PRIMARY KEY (`polId`),
  INDEX `partyId_idx` (`partyId` ASC),
  INDEX `platformId_idx` (`platformId` ASC),
  CONSTRAINT `partyId`
    FOREIGN KEY (`partyId`)
    REFERENCES `DB_Lab`.`party` (`partyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `platformId`
    FOREIGN KEY (`platformId`)
    REFERENCES `DB_Lab`.`platform` (`platformId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Lab`.`positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Lab`.`positions` ;

CREATE TABLE IF NOT EXISTS `DB_Lab`.`positions` (
  `positionId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`positionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Lab`.`elections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Lab`.`elections` ;

CREATE TABLE IF NOT EXISTS `DB_Lab`.`elections` (
  `electionId` INT NOT NULL AUTO_INCREMENT,
  `positionId` INT NOT NULL,
  `dateTime` DATETIME NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`electionId`),
  INDEX `positionId_idx` (`positionId` ASC),
  CONSTRAINT `positionId`
    FOREIGN KEY (`positionId`)
    REFERENCES `DB_Lab`.`positions` (`positionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Lab`.`candidates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Lab`.`candidates` ;

CREATE TABLE IF NOT EXISTS `DB_Lab`.`candidates` (
  `polId` INT NOT NULL,
  `electionId` INT NOT NULL,
  PRIMARY KEY (`polId`, `electionId`),
  INDEX `electionId_idx` (`electionId` ASC),
  CONSTRAINT `accountId`
    FOREIGN KEY (`polId`)
    REFERENCES `DB_Lab`.`politicians` (`polId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `electionId`
    FOREIGN KEY (`electionId`)
    REFERENCES `DB_Lab`.`elections` (`electionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Lab`.`sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Lab`.`sessions` ;

CREATE TABLE IF NOT EXISTS `DB_Lab`.`favorites` (
  `sessionId`INT NOT NULL,
  `UID` INT NOT NULL,
  `type` INT(1) NOT NULL,
  `expirationDate` DATETIME NOT NULL,
  PRIMARY KEY(`sessionId`)
  CONSTRAINT `IDNONPOL`
    FOREIGN KEY (`UID`)
    REFERENCES `DB_Lab`.`nonPolitician` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IDPOL`
    FOREIGN KEY (`UID`)
    REFERENCES `DB_Lab`.`politicians` (`polId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `DB_Lab`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Lab`.`favorites` ;

CREATE TABLE IF NOT EXISTS `DB_Lab`.`favorites` (
  `userId` INT NOT NULL,
  `polId` INT NOT NULL,
  PRIMARY KEY (`userId`, `polId`),
  INDEX `polId_idx` (`polId` ASC),
  CONSTRAINT `userID`
    FOREIGN KEY (`UID`)
    REFERENCES `DB_Lab`.`nonPolitician` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `polId`
    FOREIGN KEY (`UID`)
    REFERENCES `DB_Lab`.`politicians` (`polId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Lab`.`phone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Lab`.`phone` ;

CREATE TABLE IF NOT EXISTS `DB_Lab`.`phone` (
  `phoneId` INT NOT NULL AUTO_INCREMENT,
  `UID` INT NOT NULL,
  `accountType` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `number` INT(10) NOT NULL,
  PRIMARY KEY (`phoneId`),
  INDEX `IDPOL_idx` (`UID` ASC),
  CONSTRAINT `IDNONPOL`
    FOREIGN KEY (`UID`)
    REFERENCES `DB_Lab`.`nonPolitician` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IDPOL`
    FOREIGN KEY (`UID`)
    REFERENCES `DB_Lab`.`politicians` (`polId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Lab`.`pictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Lab`.`pictures` ;

CREATE TABLE IF NOT EXISTS `DB_Lab`.`pictures` (
  `partyId` INT NOT NULL,
  `picture` BLOB NULL,
  PRIMARY KEY (`partyId`),
  CONSTRAINT `fk_pictures_1`
    FOREIGN KEY (`partyId`)
    REFERENCES `DB_Lab`.`party` (`partyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `DB_Lab`.`nonPolitician`
-- -----------------------------------------------------
START TRANSACTION;
USE `DB_Lab`;
INSERT INTO `DB_Lab`.`nonPolitician` (`username`,`password`,`email`,`picture`,`firstName`,`lastName`,`phone`) VALUES ('yyyy','password','abe@gmail.com',null,'Abe','Willian',null);
INSERT INTO `DB_Lab`.`nonPolitician` (`username`,`password`,`email`,`picture`,`firstName`,`lastName`,`phone`) VALUES ('rc32','123',null,null,'Weaver','Bob',null);
INSERT INTO `DB_Lab`.`nonPolitician` (`username`,`password`,`email`,`picture`,`firstName`,`lastName`,`phone`) VALUES ('i11Pc','abc','will2@smu.edu',null,'Will','Roberson',null);

COMMIT;
-- -----------------------------------------------------
-- Data for table `DB_Lab`.`party`
-- -----------------------------------------------------
START TRANSACTION;
USE `DB_Lab`;
INSERT INTO `DB_Lab`.`party` (`partyName`) VALUES ('Republican');
INSERT INTO `DB_Lab`.`party` (`partyName`) VALUES ('Democrat');
INSERT INTO `DB_Lab`.`party` (`partyName`) VALUES ('Libertarian');
INSERT INTO `DB_Lab`.`party` (`partyName`) VALUES ('Tea Party');
INSERT INTO `DB_Lab`.`party` (`partyName`) VALUES ('Illuminati');

COMMIT;


-- -----------------------------------------------------
-- Data for table `DB_Lab`.`platform`
-- -----------------------------------------------------
START TRANSACTION;
USE `DB_Lab`;
INSERT INTO `DB_Lab`.`platform` (`platformName`) VALUES ('Gun Control');
INSERT INTO `DB_Lab`.`platform` (`platformName`) VALUES ('Immigration');

COMMIT;


-- -----------------------------------------------------
-- Data for table `DB_Lab`.`politicians`
-- -----------------------------------------------------
START TRANSACTION;
USE `DB_Lab`;
INSERT INTO `DB_Lab`.`politicians` (`username`, `password`, `email`, `picture`, `firstName`, `lastName`, `partyId`, `phone`, `website`, `platformId`) VALUES ('Jsmith', 'smithy', 'jsmith@rep.gov', NULL, 'John', 'Smith', 1, NULL, NULL, NULL);
INSERT INTO `DB_Lab`.`politicians` (`username`, `password`, `email`, `picture`, `firstName`, `lastName`, `partyId`, `phone`, `website`, `platformId`) VALUES ('Rwilliams', 'freewilly', 'rwilliams@dem.gov', NULL, 'Rebeccah', 'Williams', 2, NULL, NULL, 1);
INSERT INTO `DB_Lab`.`politicians` (`username`, `password`, `email`, `picture`, `firstName`, `lastName`, `partyId`, `phone`, `website`, `platformId`) VALUES ('Broham', 'brosbeforehoes', 'broham@teaparty.org', NULL, 'Barry', 'Roham', 3, NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `DB_Lab`.`positions`
-- -----------------------------------------------------
START TRANSACTION;
USE `DB_Lab`;
INSERT INTO `DB_Lab`.`positions` (`name`) VALUES ('Governor');
INSERT INTO `DB_Lab`.`positions` (`name`) VALUES ('Senator');
INSERT INTO `DB_Lab`.`positions` (`name`) VALUES ('Representative');
INSERT INTO `DB_Lab`.`positions` (`name`) VALUES ('Judge');

COMMIT;


-- -----------------------------------------------------
-- Data for table `DB_Lab`.`elections`
-- -----------------------------------------------------
START TRANSACTION;
USE `DB_Lab`;
INSERT INTO `DB_Lab`.`elections` (`positionId`, `dateTime`, `city`, `state`) VALUES (1, '2018-10-12', 'Austin', 'TX');
INSERT INTO `DB_Lab`.`elections` (`positionId`, `dateTime`, `city`, `state`) VALUES (2, '2020-02-24', 'Cincinnatti', 'CT');
INSERT INTO `DB_Lab`.`elections` (`positionId`, `dateTime`, `city`, `state`) VALUES (3, '2020-03-23', 'Rhode Island', 'MA');

COMMIT;


-- -----------------------------------------------------
-- Data for table `DB_Lab`.`candidates`
-- -----------------------------------------------------
START TRANSACTION;
USE `DB_Lab`;
INSERT INTO `DB_Lab`.`candidates` (`polId`, `electionId`) VALUES (1, 1);
INSERT INTO `DB_Lab`.`candidates` (`polId`, `electionId`) VALUES (2, 3);
INSERT INTO `DB_Lab`.`candidates` (`polId`, `electionId`) VALUES (3, 2);

COMMIT;

-- -----------------------------------------------------
-- Data for table `DB_Lab`.`favorites`
-- -----------------------------------------------------
START TRANSACTION;
USE  `DB_Lab`;
INSERT INTO `DB_Lab`.`favorites` (`userId`, `polId`) VALUES (1, 1);
INSERT INTO `DB_Lab`.`favorites` (`userId`, `polId`) VALUES (1, 2);
INSERT INTO `DB_Lab`.`favorites` (`userId`, `polId`) VALUES (2, 2);
INSERT INTO `DB_Lab`.`favorites` (`userId`, `polId`) VALUES (3, 3);

COMMIT;